var group___f_m_c___l_l___private___macros =
[
    [ "FMC TCLR Setup Time", "group___f_m_c___t_c_l_r___setup___time.html", "group___f_m_c___t_c_l_r___setup___time" ],
    [ "FMC TAR Setup Time", "group___f_m_c___t_a_r___setup___time.html", "group___f_m_c___t_a_r___setup___time" ],
    [ "FMC Setup Time", "group___f_m_c___setup___time.html", "group___f_m_c___setup___time" ],
    [ "FMC Wait Setup Time", "group___f_m_c___wait___setup___time.html", "group___f_m_c___wait___setup___time" ],
    [ "FMC Hold Setup Time", "group___f_m_c___hold___setup___time.html", "group___f_m_c___hold___setup___time" ],
    [ "FMC HiZ Setup Time", "group___f_m_c___hi_z___setup___time.html", "group___f_m_c___hi_z___setup___time" ],
    [ "FMC Data Latency", "group___f_m_c___data___latency.html", "group___f_m_c___data___latency" ],
    [ "FMC Address Setup Time", "group___f_m_c___address___setup___time.html", "group___f_m_c___address___setup___time" ],
    [ "FMC Address Hold Time", "group___f_m_c___address___hold___time.html", "group___f_m_c___address___hold___time" ],
    [ "FMC Data Setup Time", "group___f_m_c___data___setup___time.html", "group___f_m_c___data___setup___time" ],
    [ "FMC Bus Turn around Duration", "group___f_m_c___bus___turn__around___duration.html", "group___f_m_c___bus___turn__around___duration" ],
    [ "FMC CLK Division", "group___f_m_c___c_l_k___division.html", "group___f_m_c___c_l_k___division" ],
    [ "FMC SDRAM LoadToActive Delay", "group___f_m_c___s_d_r_a_m___load_to_active___delay.html", "group___f_m_c___s_d_r_a_m___load_to_active___delay" ],
    [ "FMC SDRAM ExitSelfRefresh Delay", "group___f_m_c___s_d_r_a_m___exit_self_refresh___delay.html", "group___f_m_c___s_d_r_a_m___exit_self_refresh___delay" ],
    [ "FMC SDRAM SelfRefresh Time", "group___f_m_c___s_d_r_a_m___self_refresh___time.html", "group___f_m_c___s_d_r_a_m___self_refresh___time" ],
    [ "FMC SDRAM RowCycle Delay", "group___f_m_c___s_d_r_a_m___row_cycle___delay.html", "group___f_m_c___s_d_r_a_m___row_cycle___delay" ],
    [ "FMC SDRAM Write Recovery Time", "group___f_m_c___s_d_r_a_m___write___recovery___time.html", "group___f_m_c___s_d_r_a_m___write___recovery___time" ],
    [ "FMC SDRAM RP Delay", "group___f_m_c___s_d_r_a_m___r_p___delay.html", "group___f_m_c___s_d_r_a_m___r_p___delay" ],
    [ "FMC SDRAM RCD Delay", "group___f_m_c___s_d_r_a_m___r_c_d___delay.html", "group___f_m_c___s_d_r_a_m___r_c_d___delay" ],
    [ "FMC SDRAM AutoRefresh Number", "group___f_m_c___s_d_r_a_m___auto_refresh___number.html", "group___f_m_c___s_d_r_a_m___auto_refresh___number" ],
    [ "FMC SDRAM ModeRegister Definition", "group___f_m_c___s_d_r_a_m___mode_register___definition.html", "group___f_m_c___s_d_r_a_m___mode_register___definition" ],
    [ "FMC SDRAM Refresh rate", "group___f_m_c___s_d_r_a_m___refresh__rate.html", "group___f_m_c___s_d_r_a_m___refresh__rate" ],
    [ "FMC NORSRAM Device Instance", "group___f_m_c___n_o_r_s_r_a_m___device___instance.html", "group___f_m_c___n_o_r_s_r_a_m___device___instance" ],
    [ "FMC NORSRAM EXTENDED Device Instance", "group___f_m_c___n_o_r_s_r_a_m___e_x_t_e_n_d_e_d___device___instance.html", "group___f_m_c___n_o_r_s_r_a_m___e_x_t_e_n_d_e_d___device___instance" ],
    [ "FMC NAND Device Instance", "group___f_m_c___n_a_n_d___device___instance.html", "group___f_m_c___n_a_n_d___device___instance" ],
    [ "FMC SDRAM Device Instance", "group___f_m_c___s_d_r_a_m___device___instance.html", "group___f_m_c___s_d_r_a_m___device___instance" ],
    [ "FMC NOR/SRAM Macros", "group___f_m_c___l_l___n_o_r___macros.html", "group___f_m_c___l_l___n_o_r___macros" ],
    [ "FMC NAND Macros", "group___f_m_c___l_l___n_a_n_d___macros.html", "group___f_m_c___l_l___n_a_n_d___macros" ],
    [ "FMC Interrupt", "group___f_m_c___interrupt.html", "group___f_m_c___interrupt" ],
    [ "IS_FMC_ACCESS_MODE", "group___f_m_c___l_l___private___macros.html#gab45579566f53756a93ae84d15922db5f", null ],
    [ "IS_FMC_ASYNWAIT", "group___f_m_c___l_l___private___macros.html#ga41a6c6b8e61711609c2b1c7092af5b4c", null ],
    [ "IS_FMC_BURSTMODE", "group___f_m_c___l_l___private___macros.html#ga8ee4ea72b19ce42032042ef40d71d8a0", null ],
    [ "IS_FMC_CAS_LATENCY", "group___f_m_c___l_l___private___macros.html#ga451b1f92c5d11737046e5c5a43b0e514", null ],
    [ "IS_FMC_COLUMNBITS_NUMBER", "group___f_m_c___l_l___private___macros.html#ga797129e2dfa1611b0692eb4ae7563183", null ],
    [ "IS_FMC_COMMAND_MODE", "group___f_m_c___l_l___private___macros.html#gaa6729b1267d2487bcb3c0766394ee3ad", null ],
    [ "IS_FMC_COMMAND_TARGET", "group___f_m_c___l_l___private___macros.html#ga69cadb51fb2b16bfed4c1867f6a38a76", null ],
    [ "IS_FMC_CONTINOUS_CLOCK", "group___f_m_c___l_l___private___macros.html#ga3171277af9c6cae158714b5e9d03df6a", null ],
    [ "IS_FMC_ECC_STATE", "group___f_m_c___l_l___private___macros.html#ga97410a9034aa259fa87db6fe3c2f994d", null ],
    [ "IS_FMC_ECCPAGE_SIZE", "group___f_m_c___l_l___private___macros.html#ga932ac250f7d285ffba183da9de6651a0", null ],
    [ "IS_FMC_EXTENDED_MODE", "group___f_m_c___l_l___private___macros.html#ga4f2d212064380f3558a355a35d502129", null ],
    [ "IS_FMC_INTERNALBANK_NUMBER", "group___f_m_c___l_l___private___macros.html#ga070e68d7057db44c058b3a999dec5b15", null ],
    [ "IS_FMC_MEMORY", "group___f_m_c___l_l___private___macros.html#ga65201c4e5988afaf4c14d8c3d451458a", null ],
    [ "IS_FMC_MUX", "group___f_m_c___l_l___private___macros.html#gad87f37e2727d76c5ae4db83123968694", null ],
    [ "IS_FMC_NAND_BANK", "group___f_m_c___l_l___private___macros.html#gadae9879205f31bbb0bf2f921243602fc", null ],
    [ "IS_FMC_NAND_MEMORY_WIDTH", "group___f_m_c___l_l___private___macros.html#ga9bbe19f314b2148cb573c9486f45a1b3", null ],
    [ "IS_FMC_NORSRAM_BANK", "group___f_m_c___l_l___private___macros.html#ga511792904b72197bcea6e10c8b5f0508", null ],
    [ "IS_FMC_NORSRAM_MEMORY_WIDTH", "group___f_m_c___l_l___private___macros.html#ga2ebc54cd97fd88ad6286338fce3ffe48", null ],
    [ "IS_FMC_PAGESIZE", "group___f_m_c___l_l___private___macros.html#ga0aea060c641910bdadc1f48044f2ed8f", null ],
    [ "IS_FMC_READ_BURST", "group___f_m_c___l_l___private___macros.html#gafda7de8481c742b3f11b368abf37037c", null ],
    [ "IS_FMC_READPIPE_DELAY", "group___f_m_c___l_l___private___macros.html#ga782b8f96953251d1ad51f0e04821f2ad", null ],
    [ "IS_FMC_ROWBITS_NUMBER", "group___f_m_c___l_l___private___macros.html#ga1f3069d81dea6851e662f12b3c1ef48f", null ],
    [ "IS_FMC_SDCLOCK_PERIOD", "group___f_m_c___l_l___private___macros.html#gab8da2c2718d93e50fa8069ae0026da71", null ],
    [ "IS_FMC_SDMEMORY_WIDTH", "group___f_m_c___l_l___private___macros.html#ga3b96d13ed33305aeebdc876c6579f84f", null ],
    [ "IS_FMC_SDRAM_BANK", "group___f_m_c___l_l___private___macros.html#ga6e6ad53e86e94a04771139e4f27e6405", null ],
    [ "IS_FMC_WAIT_FEATURE", "group___f_m_c___l_l___private___macros.html#gaad556bf07b9677e683abd6a94f9ee9f8", null ],
    [ "IS_FMC_WAIT_POLARITY", "group___f_m_c___l_l___private___macros.html#ga3e45c42296be40252db7166cab9c2957", null ],
    [ "IS_FMC_WAIT_SIGNAL_ACTIVE", "group___f_m_c___l_l___private___macros.html#ga60a02187e4d7ea8c535150859180bfac", null ],
    [ "IS_FMC_WAITE_SIGNAL", "group___f_m_c___l_l___private___macros.html#gac78f27571ace17ee6b78dfa8142a31be", null ],
    [ "IS_FMC_WRITE_BURST", "group___f_m_c___l_l___private___macros.html#gaa086b431bbb5a722303649cacdf5963f", null ],
    [ "IS_FMC_WRITE_FIFO", "group___f_m_c___l_l___private___macros.html#ga507a7489e5416486f92a2edf841ad915", null ],
    [ "IS_FMC_WRITE_OPERATION", "group___f_m_c___l_l___private___macros.html#ga441e854710b80b55470e998a3040a452", null ],
    [ "IS_FMC_WRITE_PROTECTION", "group___f_m_c___l_l___private___macros.html#ga56ef3ab18901d4fa2b33ebd3ffe0cac8", null ]
];