var group___s_a_i___exported___constants =
[
    [ "SAI Error Code", "group___s_a_i___error___code.html", "group___s_a_i___error___code" ],
    [ "SAI External synchronisation", "group___s_a_i___block___sync_ext.html", "group___s_a_i___block___sync_ext" ],
    [ "SAI Supported protocol", "group___s_a_i___protocol.html", "group___s_a_i___protocol" ],
    [ "SAI protocol data size", "group___s_a_i___protocol___data_size.html", "group___s_a_i___protocol___data_size" ],
    [ "SAI Audio Frequency", "group___s_a_i___audio___frequency.html", "group___s_a_i___audio___frequency" ],
    [ "SAI Block Mode", "group___s_a_i___block___mode.html", "group___s_a_i___block___mode" ],
    [ "SAI Block Protocol", "group___s_a_i___block___protocol.html", "group___s_a_i___block___protocol" ],
    [ "SAI Block Data Size", "group___s_a_i___block___data___size.html", "group___s_a_i___block___data___size" ],
    [ "SAI Block MSB LSB transmission", "group___s_a_i___block___m_s_b___l_s_b__transmission.html", "group___s_a_i___block___m_s_b___l_s_b__transmission" ],
    [ "SAI Block Clock Strobing", "group___s_a_i___block___clock___strobing.html", "group___s_a_i___block___clock___strobing" ],
    [ "SAI Block Synchronization", "group___s_a_i___block___synchronization.html", "group___s_a_i___block___synchronization" ],
    [ "SAI Block Output Drive", "group___s_a_i___block___output___drive.html", "group___s_a_i___block___output___drive" ],
    [ "SAI Block NoDivider", "group___s_a_i___block___no_divider.html", "group___s_a_i___block___no_divider" ],
    [ "SAI Block FS Definition", "group___s_a_i___block___f_s___definition.html", "group___s_a_i___block___f_s___definition" ],
    [ "SAI Block FS Polarity", "group___s_a_i___block___f_s___polarity.html", "group___s_a_i___block___f_s___polarity" ],
    [ "SAI Block FS Offset", "group___s_a_i___block___f_s___offset.html", "group___s_a_i___block___f_s___offset" ],
    [ "SAI Block Slot Size", "group___s_a_i___block___slot___size.html", "group___s_a_i___block___slot___size" ],
    [ "SAI Block Slot Active", "group___s_a_i___block___slot___active.html", "group___s_a_i___block___slot___active" ],
    [ "SAI Mono Stereo Mode", "group___s_a_i___mono___stereo___mode.html", "group___s_a_i___mono___stereo___mode" ],
    [ "SAI TRIState Management", "group___s_a_i___t_r_i_state___management.html", "group___s_a_i___t_r_i_state___management" ],
    [ "SAI Block Fifo Threshold", "group___s_a_i___block___fifo___threshold.html", "group___s_a_i___block___fifo___threshold" ],
    [ "SAI Block Companding Mode", "group___s_a_i___block___companding___mode.html", "group___s_a_i___block___companding___mode" ],
    [ "SAI Block Mute Value", "group___s_a_i___block___mute___value.html", "group___s_a_i___block___mute___value" ],
    [ "SAI Block Interrupts Definition", "group___s_a_i___block___interrupts___definition.html", "group___s_a_i___block___interrupts___definition" ],
    [ "SAI Block Flags Definition", "group___s_a_i___block___flags___definition.html", "group___s_a_i___block___flags___definition" ],
    [ "SAI Block Fifo Status Level", "group___s_a_i___block___fifo___status___level.html", "group___s_a_i___block___fifo___status___level" ]
];